language: php

php:
  - 7.2

services:
  - memcached

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
  - vendor/bin/phpunit --bootstrap=vendor/autoload.php tests/
